import { CanvasNode, ComponentRegistry } from '../types/builder';

export interface CodegenResult {
  code: string;
  lineMap: Record<string, { startLine: number; endLine: number }>;
}

/**
 * Pure function: Deterministically generates compilable Java Swing source code
 * and corresponding node line-mapping from a CanvasNode tree and ComponentRegistry.
 * 
 * Invariant: ZERO imports from React, Zustand, DOM, or src/components/.
 */
export function generateJavaCode(
  tree: CanvasNode | null,
  registry: ComponentRegistry
): CodegenResult {
  if (!tree) {
    return {
      code: '// Empty canvas. Add a JFrame to generate Java Swing code.\n',
      lineMap: {},
    };
  }

  const lineMap: Record<string, { startLine: number; endLine: number }> = {};
  const outputLines: string[] = [];

  function emit(line: string) {
    outputLines.push(line);
  }

  // 1. Collect all distinct component types in tree to determine imports
  const usedImports = new Set<string>();
  usedImports.add('javax.swing.*');
  usedImports.add('java.awt.*');

  function collectImports(node: CanvasNode) {
    const entry = registry[node.type];
    if (entry?.javaImport) {
      usedImports.add(entry.javaImport);
    }
    for (const child of node.children) {
      collectImports(child);
    }
  }
  collectImports(tree);

  // 2. Collect all variable declarations (excluding root JFrame which is 'this')
  const declarations: { type: string; varName: string; id: string }[] = [];
  function collectDeclarations(node: CanvasNode) {
    if (node.id !== tree?.id) {
      declarations.push({
        type: node.type,
        varName: node.varName,
        id: node.id,
      });
    }
    for (const child of node.children) {
      collectDeclarations(child);
    }
  }
  collectDeclarations(tree);

  // --- Start Emitting Code ---
  emit('package com.ngejava.generated;');
  emit('');

  // Sorted, deterministic import statements
  const sortedImports = Array.from(usedImports).sort();
  for (const imp of sortedImports) {
    emit(`import ${imp};`);
  }
  emit('');

  emit('/**');
  emit(' * Auto-generated by JForge (NgeJava).');
  emit(' * Direct 1-way projection from JSON UI tree.');
  emit(' */');
  emit('public class GeneratedForm extends JFrame {');
  emit('');

  // Variable field declarations
  if (declarations.length > 0) {
    emit('    // Variables declaration - do not modify');
    for (const decl of declarations) {
      emit(`    private ${decl.type} ${decl.varName};`);
    }
    emit('    // End of variables declaration');
    emit('');
  }

  // Constructor
  emit('    public GeneratedForm() {');
  emit('        initComponents();');
  emit('    }');
  emit('');

  // initComponents method
  emit('    @SuppressWarnings("unchecked")');
  emit('    private void initComponents() {');

  // Root JFrame configuration statements
  const rootEntry = registry[tree.type];
  const rootStartLine = outputLines.length + 1;
  if (rootEntry) {
    const rootCode = rootEntry.codeTemplate(tree);
    const rootCodeLines = rootCode.split('\n');
    for (const cl of rootCodeLines) {
      emit(`        ${cl}`);
    }
  }
  const rootEndLine = outputLines.length;
  lineMap[tree.id] = { startLine: rootStartLine, endLine: rootEndLine };

  // Recursive emitter for container children
  function emitContainerChildren(containerNode: CanvasNode) {
    for (const child of containerNode.children) {
      const childEntry = registry[child.type];
      const childStartLine = outputLines.length + 1;

      emit('');
      emit(`        // ---- ${child.varName} (${child.type}) ----`);

      if (childEntry) {
        const statements = childEntry.codeTemplate(child).split('\n');
        for (const stmt of statements) {
          emit(`        ${stmt}`);
        }
      }

      // Add to parent container:
      // If parent is root JFrame, use getContentPane().add(...) or add(...)
      if (containerNode.id === tree?.id) {
        emit(`        getContentPane().add(${child.varName});`);
      } else {
        emit(`        ${containerNode.varName}.add(${child.varName});`);
      }

      // If child is itself a container (e.g. JPanel), emit its children
      if (child.children.length > 0) {
        emitContainerChildren(child);
      }

      const childEndLine = outputLines.length;
      lineMap[child.id] = { startLine: childStartLine, endLine: childEndLine };
    }
  }

  emitContainerChildren(tree);

  emit('');
  emit('        pack();');
  if (tree.props.width && tree.props.height) {
    emit(`        setSize(${tree.props.width}, ${tree.props.height});`);
  }
  emit('        setLocationRelativeTo(null);');
  emit('        setVisible(true);');
  emit('    }');
  emit('');

  // main method entry point
  emit('    public static void main(String[] args) {');
  emit('        EventQueue.invokeLater(() -> {');
  emit('            new GeneratedForm();');
  emit('        });');
  emit('    }');
  emit('}');
  emit('');

  return {
    code: outputLines.join('\n'),
    lineMap,
  };
}
